import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";

const font = Montserrat({
  subsets: ["latin"], weight: ["100","400", "500", "700"], });

export const metadata: Metadata = {
  title: "Next Role",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased bg-soft-gray`}
      >
        {children}
      </body>
    </html>
  );
}
