import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import CookiesConsent from "@/components/CookiesConsent";

const font = Inter({
  subsets: ["latin"],
  weight: ["100", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Next Role",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${font.className} antialiased bg-soft-gray relative`}>
       
        {children}
        <CookiesConsent />
      
      </body>
    </html>
  );
}
