import {
  Home,
  User,
  Settings,
  Search,
  Menu,
  MoreHorizontal,
  MoreVertical,
  Grid3X3,
  List,
  Filter,
  SortAsc,
  SortDesc,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowUpDown,
  ArrowLeftRight,
  ArrowUpRight,
  ArrowDownRight,
  ArrowUpLeft,
  ArrowDownLeft,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ChevronFirst,
  ChevronLast,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  ChevronsDown,
  Plus,
  Minus,
  X,
  Check,
  Edit,
  Trash2,
  Copy,
  ScissorsIcon as Cut,
  ClipboardPasteIcon as Paste,
  Save,
  Download,
  Upload,
  Share,
  Send,
  RefreshCwIcon as Refresh,
  RotateCcw,
  RotateCw,
  Play,
  Pause,
  CircleStopIcon as Stop,
  SkipBack,
  SkipForward,
  FastForward,
  Rewind,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Shuffle,
  Repeat,
  Repeat1,
  Mail,
  MessageCircle,
  MessageSquare,
  Phone,
  PhoneCall,
  PhoneIncoming,
  PhoneOutgoing,
  Video,
  VideoOff,
  Mic,
  MicOff,
  Users,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Share2,
  Forward,
  Reply,
  ReplyAll,
  Image,
  Camera,
  VideoIcon,
  Music,
  Music2,
  Music3,
  Music4,
  File,
  FileText,
  FileImage,
  FileVideo,
  FileAudio,
  Folder,
  FolderOpen,
  FolderPlus,
  Archive,
  Package,
  Package2,
  PackageOpen,
  Paperclip,
  Link,
  Link2,
  ExternalLink,
  Eye,
  EyeOff,
  Maximize,
  Maximize2,
  Minimize,
  Minimize2,
  Move,
  ScalingIcon as Resize,
  Crop,
  Scissors,
  PaintBucket,
  Palette,
  Brush,
  Layout,
  LayoutGrid,
  LayoutList,
  Sidebar,
  SidebarOpen,
  SidebarClose,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  Bell,
  BellOff,
  BellRing,
  AlertCircle,
  AlertTriangle,
  Info,
  CheckCircle,
  CheckCircle2,
  XCircle,
  HelpCircle,
  AlertOctagon,
  Loader,
  Loader2,
  Clock,
  TimerIcon as Time,
  Hourglass,
  Activity,
  TrendingUp,
  TrendingDown,
  BarChart,
  BarChart3,
  LineChart,
  Lock,
  Unlock,
  Key,
  Shield,
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  Fingerprint,
  Scan,
  ScanLine,
  QrCode,
  Wifi,
  WifiOff,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Umbrella,
  Rainbow,
  Snowflake,
  Droplets,
  Wind,
  Thermometer,
  TreesIcon as Tree,
  Flower,
  Flower2,
  Leaf,
  Sprout,
  Bug,
  Fish,
  Bird,
  Rabbit,
  Dog,
  Cat,
  Car,
  Truck,
  Bus,
  Bike,
  Plane,
  Train,
  Ship,
  Rocket,
  MapPin,
  Map,
  Navigation,
  Navigation2,
  Compass,
  Globe,
  Globe2,
  Building,
  Building2,
  HomeIcon as House,
  Store,
  Hospital,
  School,
  Church,
  Factory,
  Warehouse,
  Hotel,
  Landmark,
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  Banknote,
  Coins,
  Receipt,
  Tag,
  Tags,
  Gift,
  GiftIcon as GiftCard,
  Percent,
  DollarSign,
  Target,
  Award,
  Trophy,
  Medal,
  Star,
  StarHalf,
  Bookmark,
  BookmarkPlus,
  Wrench,
  Hammer,
  WrenchIcon as Screwdriver,
  Drill,
  SirenIcon as Saw,
  Ruler,
  Pin,
  PinIcon as Pushpin,
  Magnet,
  Lightbulb,
  Flashlight,
  CandlestickChartIcon as Candle,
  Flame,
  Zap,
  Battery,
  BatteryLow,
  Plug,
  Power,
  PowerOff,
  Coffee,
  CupSodaIcon as Cup,
  Wine,
  Beer,
  Pizza,
  Apple,
  Cherry,
  Grape,
  IceCream,
  Cake,
  Cookie,
  Utensils,
  UtensilsCrossed,
  Smartphone,
  Tablet,
  Laptop,
  Monitor,
  Tv,
  Radio,
  Headphones,
  Speaker,
  Keyboard,
  Mouse,
  Printer,
  ScanIcon as Scanner,
  HardDrive,
  Cpu,
  MemoryStick,
  Usb,
  Bluetooth,
  Router,
  Server,
  Database,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Indent,
  Outdent,
  Quote,
  Hash,
  AtSign,
  Ampersand,
  Asterisk,
  Slash,
  SlashIcon as Backslash,
  PipetteIcon as Pipe,
  AmpersandIcon as Tilde,
  Gamepad,
  Gamepad2,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Puzzle,
  Crosshair,
  Joystick,
  Calendar,
  CalendarDays,
  CalendarCheck,
  CalendarX,
  CalendarPlus,
  Clock1,
  Clock2,
  Clock3,
  Clock4,
  Clock5,
  Clock6,
  Clock7,
  Clock8,
  Clock9,
  Clock10,
  Clock11,
  Clock12,
  AlarmClock,
  Sparkles,
  Sparkle,
  Gem,
  Diamond,
  Crown,
  Feather,
  Mountain,
  MountainIcon as Mountains,
  Waves,
  type LucideIcon,
  BarChart2,
} from "lucide-react"

export interface IconItem {
  name: string
  icon: LucideIcon
}

export const iconCategories = {
  general: [
    { name: "Home", icon: Home },
    { name: "User", icon: User },
    { name: "Settings", icon: Settings },
    { name: "Search", icon: Search },
    { name: "Menu", icon: Menu },
    { name: "MoreHorizontal", icon: MoreHorizontal },
    { name: "MoreVertical", icon: MoreVertical },
    { name: "Grid3X3", icon: Grid3X3 },
    { name: "List", icon: List },
    { name: "Filter", icon: Filter },
    { name: "SortAsc", icon: SortAsc },
    { name: "SortDesc", icon: SortDesc },
  ],
  navigation: [
    { name: "ArrowLeft", icon: ArrowLeft },
    { name: "ArrowRight", icon: ArrowRight },
    { name: "ArrowUp", icon: ArrowUp },
    { name: "ArrowDown", icon: ArrowDown },
    { name: "ArrowUpDown", icon: ArrowUpDown },
    { name: "ArrowLeftRight", icon: ArrowLeftRight },
    { name: "ArrowUpRight", icon: ArrowUpRight },
    { name: "ArrowDownRight", icon: ArrowDownRight },
    { name: "ArrowUpLeft", icon: ArrowUpLeft },
    { name: "ArrowDownLeft", icon: ArrowDownLeft },
    { name: "ChevronLeft", icon: ChevronLeft },
    { name: "ChevronRight", icon: ChevronRight },
    { name: "ChevronUp", icon: ChevronUp },
    { name: "ChevronDown", icon: ChevronDown },
    { name: "ChevronFirst", icon: ChevronFirst },
    { name: "ChevronLast", icon: ChevronLast },
    { name: "ChevronsLeft", icon: ChevronsLeft },
    { name: "ChevronsRight", icon: ChevronsRight },
    { name: "ChevronsUp", icon: ChevronsUp },
    { name: "ChevronsDown", icon: ChevronsDown },
  ],
  actions: [
    { name: "Plus", icon: Plus },
    { name: "Minus", icon: Minus },
    { name: "X", icon: X },
    { name: "Check", icon: Check },
    { name: "Edit", icon: Edit },
    { name: "Trash2", icon: Trash2 },
    { name: "Copy", icon: Copy },
    { name: "Cut", icon: Cut },
    { name: "Paste", icon: Paste },
    { name: "Save", icon: Save },
    { name: "Download", icon: Download },
    { name: "Upload", icon: Upload },
    { name: "Share", icon: Share },
    { name: "Send", icon: Send },
    { name: "Refresh", icon: Refresh },
    { name: "RotateCcw", icon: RotateCcw },
    { name: "RotateCw", icon: RotateCw },
  ],
  media: [
    { name: "Play", icon: Play },
    { name: "Pause", icon: Pause },
    { name: "Stop", icon: Stop },
    { name: "SkipBack", icon: SkipBack },
    { name: "SkipForward", icon: SkipForward },
    { name: "FastForward", icon: FastForward },
    { name: "Rewind", icon: Rewind },
    { name: "Volume", icon: Volume },
    { name: "Volume1", icon: Volume1 },
    { name: "Volume2", icon: Volume2 },
    { name: "VolumeX", icon: VolumeX },
    { name: "Shuffle", icon: Shuffle },
    { name: "Repeat", icon: Repeat },
    { name: "Repeat1", icon: Repeat1 },
    { name: "Image", icon: Image },
    { name: "Camera", icon: Camera },
    { name: "Video", icon: VideoIcon },
    { name: "Music", icon: Music },
    { name: "Music2", icon: Music2 },
    { name: "Music3", icon: Music3 },
    { name: "Music4", icon: Music4 },
  ],
  communication: [
    { name: "Mail", icon: Mail },
    { name: "MessageCircle", icon: MessageCircle },
    { name: "MessageSquare", icon: MessageSquare },
    { name: "Phone", icon: Phone },
    { name: "PhoneCall", icon: PhoneCall },
    { name: "PhoneIncoming", icon: PhoneIncoming },
    { name: "PhoneOutgoing", icon: PhoneOutgoing },
    { name: "Video2", icon: Video },
    { name: "VideoOff", icon: VideoOff },
    { name: "Mic", icon: Mic },
    { name: "MicOff", icon: MicOff },
    { name: "Users", icon: Users },
    { name: "UserPlus", icon: UserPlus },
    { name: "UserMinus", icon: UserMinus },
    { name: "UserCheck", icon: UserCheck },
    { name: "UserX", icon: UserX },
    { name: "Heart", icon: Heart },
    { name: "ThumbsUp", icon: ThumbsUp },
    { name: "ThumbsDown", icon: ThumbsDown },
    { name: "Share2", icon: Share2 },
    { name: "Forward", icon: Forward },
    { name: "Reply", icon: Reply },
    { name: "ReplyAll", icon: ReplyAll },
  ],
  files: [
    { name: "File", icon: File },
    { name: "FileText", icon: FileText },
    { name: "FileImage", icon: FileImage },
    { name: "FileVideo", icon: FileVideo },
    { name: "FileAudio", icon: FileAudio },
    { name: "Folder", icon: Folder },
    { name: "FolderOpen", icon: FolderOpen },
    { name: "FolderPlus", icon: FolderPlus },
    { name: "Archive", icon: Archive },
    { name: "Package", icon: Package },
    { name: "Package2", icon: Package2 },
    { name: "PackageOpen", icon: PackageOpen },
    { name: "Paperclip", icon: Paperclip },
    { name: "Link", icon: Link },
    { name: "Link2", icon: Link2 },
    { name: "ExternalLink", icon: ExternalLink },
  ],
  interface: [
    { name: "Eye", icon: Eye },
    { name: "EyeOff", icon: EyeOff },
    { name: "Maximize", icon: Maximize },
    { name: "Maximize2", icon: Maximize2 },
    { name: "Minimize", icon: Minimize },
    { name: "Minimize2", icon: Minimize2 },
    { name: "Move", icon: Move },
    { name: "Resize", icon: Resize },
    { name: "Crop", icon: Crop },
    { name: "Scissors", icon: Scissors },
    { name: "PaintBucket", icon: PaintBucket },
    { name: "Palette", icon: Palette },
    { name: "Brush", icon: Brush },
    { name: "Layout", icon: Layout },
    { name: "LayoutGrid", icon: LayoutGrid },
    { name: "LayoutList", icon: LayoutList },
    { name: "Sidebar", icon: Sidebar },
    { name: "SidebarOpen", icon: SidebarOpen },
    { name: "SidebarClose", icon: SidebarClose },
    { name: "PanelLeft", icon: PanelLeft },
    { name: "PanelRight", icon: PanelRight },
    { name: "PanelTop", icon: PanelTop },
    { name: "PanelBottom", icon: PanelBottom },
  ],
  status: [
    { name: "Bell", icon: Bell },
    { name: "BellOff", icon: BellOff },
    { name: "BellRing", icon: BellRing },
    { name: "AlertCircle", icon: AlertCircle },
    { name: "AlertTriangle", icon: AlertTriangle },
    { name: "Info", icon: Info },
    { name: "CheckCircle", icon: CheckCircle },
    { name: "CheckCircle2", icon: CheckCircle2 },
    { name: "XCircle", icon: XCircle },
    { name: "HelpCircle", icon: HelpCircle },
    { name: "AlertOctagon", icon: AlertOctagon },
    { name: "Loader", icon: Loader },
    { name: "Loader2", icon: Loader2 },
    { name: "RefreshCw", icon: Refresh },
    { name: "Clock", icon: Clock },
    { name: "Timer", icon: Time },
    { name: "Hourglass", icon: Hourglass },
    { name: "Activity", icon: Activity },
    { name: "TrendingUp", icon: TrendingUp },
    { name: "TrendingDown", icon: TrendingDown },
    { name: "BarChart", icon: BarChart },
    { name: "BarChart2", icon: BarChart2 },
    { name: "BarChart3", icon: BarChart3 },
    { name: "LineChart", icon: LineChart },
  ],
  security: [
    { name: "Lock", icon: Lock },
    { name: "Unlock", icon: Unlock },
    { name: "Key", icon: Key },
    { name: "Shield", icon: Shield },
    { name: "ShieldCheck", icon: ShieldCheck },
    { name: "ShieldAlert", icon: ShieldAlert },
    { name: "ShieldX", icon: ShieldX },
    { name: "Fingerprint", icon: Fingerprint },
    { name: "Scan", icon: Scan },
    { name: "ScanLine", icon: ScanLine },
    { name: "QrCode", icon: QrCode },
    { name: "Wifi", icon: Wifi },
    { name: "WifiOff", icon: WifiOff },
  ],
  weather: [
    { name: "Sun", icon: Sun },
    { name: "Moon", icon: Moon },
    { name: "Cloud", icon: Cloud },
    { name: "CloudRain", icon: CloudRain },
    { name: "CloudSnow", icon: CloudSnow },
    { name: "CloudLightning", icon: CloudLightning },
    { name: "Umbrella", icon: Umbrella },
    { name: "Rainbow", icon: Rainbow },
    { name: "Snowflake", icon: Snowflake },
    { name: "Droplets", icon: Droplets },
    { name: "Wind", icon: Wind },
    { name: "Thermometer", icon: Thermometer },
  ],
  nature: [
    { name: "Tree", icon: Tree },
    { name: "Flower", icon: Flower },
    { name: "Flower2", icon: Flower2 },
    { name: "Leaf", icon: Leaf },
    { name: "Sprout", icon: Sprout },
    { name: "Bug", icon: Bug },
    { name: "Fish", icon: Fish },
    { name: "Bird", icon: Bird },
    { name: "Rabbit", icon: Rabbit },
    { name: "Dog", icon: Dog },
    { name: "Cat", icon: Cat },
  ],
  transport: [
    { name: "Car", icon: Car },
    { name: "Truck", icon: Truck },
    { name: "Bus", icon: Bus },
    { name: "Bike", icon: Bike },
    { name: "Plane", icon: Plane },
    { name: "Train", icon: Train },
    { name: "Ship", icon: Ship },
    { name: "Rocket", icon: Rocket },
    { name: "MapPin", icon: MapPin },
    { name: "Map", icon: Map },
    { name: "Navigation", icon: Navigation },
    { name: "Navigation2", icon: Navigation2 },
    { name: "Compass", icon: Compass },
    { name: "Globe", icon: Globe },
    { name: "Globe2", icon: Globe2 },
  ],
  buildings: [
    { name: "Building", icon: Building },
    { name: "Building2", icon: Building2 },
    { name: "House", icon: House },
    { name: "Store", icon: Store },
    { name: "Hospital", icon: Hospital },
    { name: "School", icon: School },
    { name: "Church", icon: Church },
    { name: "Factory", icon: Factory },
    { name: "Warehouse", icon: Warehouse },
    { name: "Hotel", icon: Hotel },
    { name: "Landmark", icon: Landmark },
  ],
  shopping: [
    { name: "ShoppingCart", icon: ShoppingCart },
    { name: "ShoppingBag", icon: ShoppingBag },
    { name: "CreditCard", icon: CreditCard },
    { name: "Banknote", icon: Banknote },
    { name: "Coins", icon: Coins },
    { name: "Receipt", icon: Receipt },
    { name: "Tag", icon: Tag },
    { name: "Tags", icon: Tags },
    { name: "Gift", icon: Gift },
    { name: "GiftCard", icon: GiftCard },
    { name: "Percent", icon: Percent },
    { name: "DollarSign", icon: DollarSign },
    { name: "Target", icon: Target },
    { name: "Award", icon: Award },
    { name: "Trophy", icon: Trophy },
    { name: "Medal", icon: Medal },
    { name: "Star", icon: Star },
    { name: "StarHalf", icon: StarHalf },
    { name: "Bookmark", icon: Bookmark },
    { name: "BookmarkPlus", icon: BookmarkPlus },
  ],
  tools: [
    { name: "Wrench", icon: Wrench },
    { name: "Hammer", icon: Hammer },
    { name: "Screwdriver", icon: Screwdriver },
    { name: "Drill", icon: Drill },
    { name: "Saw", icon: Saw },
    { name: "Ruler", icon: Ruler },
    { name: "Pin", icon: Pin },
    { name: "Pushpin", icon: Pushpin },
    { name: "Magnet", icon: Magnet },
    { name: "Lightbulb", icon: Lightbulb },
    { name: "Flashlight", icon: Flashlight },
    { name: "Candle", icon: Candle },
    { name: "Flame", icon: Flame },
    { name: "Zap", icon: Zap },
    { name: "Battery", icon: Battery },
    { name: "BatteryLow", icon: BatteryLow },
    { name: "Plug", icon: Plug },
    { name: "Power", icon: Power },
    { name: "PowerOff", icon: PowerOff },
  ],
  technology: [
    { name: "Smartphone", icon: Smartphone },
    { name: "Tablet", icon: Tablet },
    { name: "Laptop", icon: Laptop },
    { name: "Monitor", icon: Monitor },
    { name: "Tv", icon: Tv },
    { name: "Radio", icon: Radio },
    { name: "Headphones", icon: Headphones },
    { name: "Speaker", icon: Speaker },
    { name: "Keyboard", icon: Keyboard },
    { name: "Mouse", icon: Mouse },
    { name: "Printer", icon: Printer },
    { name: "Scanner", icon: Scanner },
    { name: "HardDrive", icon: HardDrive },
    { name: "Cpu", icon: Cpu },
    { name: "MemoryStick", icon: MemoryStick },
    { name: "Usb", icon: Usb },
    { name: "Bluetooth", icon: Bluetooth },
    { name: "Router", icon: Router },
    { name: "Server", icon: Server },
    { name: "Database", icon: Database },
  ],
  text: [
    { name: "Type", icon: Type },
    { name: "Bold", icon: Bold },
    { name: "Italic", icon: Italic },
    { name: "Underline", icon: Underline },
    { name: "Strikethrough", icon: Strikethrough },
    { name: "AlignLeft", icon: AlignLeft },
    { name: "AlignCenter", icon: AlignCenter },
    { name: "AlignRight", icon: AlignRight },
    { name: "AlignJustify", icon: AlignJustify },
    { name: "Indent", icon: Indent },
    { name: "Outdent", icon: Outdent },
    { name: "Quote", icon: Quote },
    { name: "Hash", icon: Hash },
    { name: "AtSign", icon: AtSign },
    { name: "Ampersand", icon: Ampersand },
    { name: "Asterisk", icon: Asterisk },
    { name: "Slash", icon: Slash },
    { name: "Backslash", icon: Backslash },
    { name: "Pipe", icon: Pipe },
    { name: "Tilde", icon: Tilde },
  ],
  calendar: [
    { name: "Calendar", icon: Calendar },
    { name: "CalendarDays", icon: CalendarDays },
    { name: "CalendarCheck", icon: CalendarCheck },
    { name: "CalendarX", icon: CalendarX },
    { name: "CalendarPlus", icon: CalendarPlus },
    { name: "Clock1", icon: Clock1 },
    { name: "Clock2", icon: Clock2 },
    { name: "Clock3", icon: Clock3 },
    { name: "Clock4", icon: Clock4 },
    { name: "Clock5", icon: Clock5 },
    { name: "Clock6", icon: Clock6 },
    { name: "Clock7", icon: Clock7 },
    { name: "Clock8", icon: Clock8 },
    { name: "Clock9", icon: Clock9 },
    { name: "Clock10", icon: Clock10 },
    { name: "Clock11", icon: Clock11 },
    { name: "Clock12", icon: Clock12 },
    { name: "AlarmClock", icon: AlarmClock },

  ],
  gaming: [
    { name: "Gamepad", icon: Gamepad },
    { name: "Gamepad2", icon: Gamepad2 },
    { name: "Dice1", icon: Dice1 },
    { name: "Dice2", icon: Dice2 },
    { name: "Dice3", icon: Dice3 },
    { name: "Dice4", icon: Dice4 },
    { name: "Dice5", icon: Dice5 },
    { name: "Dice6", icon: Dice6 },
    { name: "Puzzle", icon: Puzzle },
    { name: "Crosshair", icon: Crosshair },
    { name: "Joystick", icon: Joystick },
  ],
  food: [
    { name: "Coffee", icon: Coffee },
    { name: "Cup", icon: Cup },
    { name: "Wine", icon: Wine },
    { name: "Beer", icon: Beer },
    { name: "Pizza", icon: Pizza },
    { name: "Apple", icon: Apple },
    { name: "Cherry", icon: Cherry },
    { name: "Grape", icon: Grape },
    { name: "IceCream", icon: IceCream },
    { name: "Cake", icon: Cake },
    { name: "Cookie", icon: Cookie },
    { name: "Utensils", icon: Utensils },
    { name: "UtensilsCrossed", icon: UtensilsCrossed },
  ],
  misc: [
    { name: "Sparkles", icon: Sparkles },
    { name: "Sparkle", icon: Sparkle },
    { name: "Gem", icon: Gem },
    { name: "Diamond", icon: Diamond },
    { name: "Crown", icon: Crown },
    { name: "Feather", icon: Feather },
    { name: "Mountain", icon: Mountain },
    { name: "Mountains", icon: Mountains },
    { name: "Waves", icon: Waves },
  ],
}