export const skillCategories = {
  Frontend: [
    "Alpine.js",
    "Angular",
    "Backbone.js",
    "Bootstrap",
    "CSS Grid Layout",
    "CSS Modules",
    "Ember.js",
    "EsLint",
    "Gatsby",
    "GraphQL",
    "HTML/CSS",
    "JavaScript",
    "Lit",
    "LitElement",
    "Mithril.js",
    "Next.js",
    "Nuxt.js",
    "PostCSS",
    "Preact",
    "React",
    "Redux",
    "SASS/SCSS",
    "Styled Components",
    "Tailwind CSS",
    "TypeScript",
    "Vue.js",
    "Web Components",
    "WebAssembly",
    "Webpack",
    "Storybook",
    "Cross-browser Compatibility",
    "Responsive Design",
    "Progressive Enhancement",
    "Graceful Degradation",
    "Web Accessibility",
    "Website Performance Optimization",
  ],

  Backend: [
    "ASP.NET",
    "C#",
    "C++",
    "Django",
    "Elixir",
    "Express.js",
    "FastAPI",
    "Flask",
    "Go",
    "GraphQL API",
    "gRPC",
    "Java",
    "Koa.js",
    "Laravel",
    "Meteor.js",
    "NestJS",
    "Node.js",
    "PHP",
    "Python",
    "Ruby",
    "Ruby on Rails",
    "Scala",
    "Shell scripting (Bash)",
    "Spring Boot",
    "Tcl",
    "WebSockets",
    "REST API",
    
  ],

  Mobile: [
    "Android Development",
    "AppGyver",
    "Appium",
    "Cordova",
    "Firebase SDK for Mobile",
    "Ionic",
    "Jetpack Compose",
    "Kotlin",
    "NativeScript",
    "Objective-C",
    "PhoneGap",
    "React Native",
    "Realm",
    "Swift",
    "SwiftUI",
    "Unity",
    "Wear OS",
    "Xamarin",
    "iOS Development",
    "React Native Navigation",
    "Flutter",
  ],

  Database: [
    "Amazon RDS",
    "Apache Kafka",
    "Cassandra",
    "CockroachDB",
    "Couchbase",
    "CouchDB",
    "Database Sharding",
    "DynamoDB",
    "Elasticsearch",
    "FaunaDB",
    "Firebase",
    "GraphQL with Database Integration",
    "IBM DB2",
    "InfluxDB",
    "MariaDB",
    "Microsoft SQL Server",
    "MongoDB",
    "MySQL",
    "Neo4j",
    "Oracle DB",
    "PostgresSQL",
    "Redis",
    "SQLite",
    "Supabase",
  ],

  "Cloud & DevOps": [
    "Alibaba Cloud",
    "Amazon Web Services (AWS)",
    "Google Cloud",
    "Ansible",
    "Apache",
    "Azure",
    "CI/CD",
    "CloudFormation",
    "Datadog",
    "DigitalOcean",
    "Docker",
    "Docker Swarm",
    "Grafana",
    "GitHub Actions",
    "GitLab CI",
    "Helm",
    "IBM Cloud",
    "Jenkins",
    "Kubernetes",
    "Linode",
    "New Relic",
    "Nginx",
    "Oracle Cloud",
    "Packer",
    "Prometheus",
    "Terraform",
    "Vault by HashiCorp",
    "Vercel",
    "Netlify",
    "CloudWatch",
  ],

  "Tools & Others": [
    "Airtable",
    "Adobe XD",
    "Asana",
    "Basecamp",
    "Bitbucket",
    "CircleCI",
    "ClickUp",
    "Docker Compose",
    "Figma",
    "Framer",
    "Git",
    "GitLab",
    "Jira",
    "Jest",
    "Linux",
    "LogRocket",
    "Monday.com",
    "Notion",
    "Photoshop",
    "Prettier",
    "Postman",
    "Sentry",
    "Slack",
    "Sketch",
    "SVN",
    "Trello",
    "VSCode",
    "Zsh",
    "Zeplin",
    "InVision",
    "Marvel App",
    "IntelliJ IDEA",
    "Unit Testing",
    "Integration Testing",
    "Software Documentation",
  ],

  "Soft Skills": [
    "Communication",
    "Leadership",
    "Teamwork",
    "Problem Solving",
    "Critical Thinking",
    "Time Management",
    "Project Management",
    "Analytical",
    "Creative",
    "Adaptable",
    "Detail-oriented",
    "Self-motivated",
    "Collaborative",
    "Mentoring",
    "Training",
    "Product Ownership",
    "Customer-centric Thinking",
  ],
};
