export const skillCategories = {
  Frontend: [
    "Alpine.js",
    "Angular",
    "Backbone.js",
    "Bootstrap",
    "CSS Grid Layout",
    "CSS Modules",
    "Ember.js",
    "EsLint",
    "Gatsby",
    "GraphQL",
    "HTML/CSS",
    "JavaScript",
    "Lit",
    "LitElement",
    "Mithril.js",
    "Next.js",
    "Nuxt.js",
    "PostCSS",
    "Preact",
    "React",
    "Redux",
    "SASS/SCSS",
    "Styled Components",
    "Tailwind CSS",
    "TypeScript",
    "Vue.js",
    "Web Components",
    "WebAssembly",
    "Webpack",
    "Storybook",
    "Cross-browser Compatibility",
    "Responsive Design",
    "Progressive Enhancement",
    "Graceful Degradation",
    "Web Accessibility",
    "Website Performance Optimization",
  ],

  Backend: [
    "ASP.NET",
    "C#",
    "C++",
    "Django",
    "Elixir",
    "Express.js",
    "FastAPI",
    "Flask",
    "Go",
    "GraphQL API",
    "gRPC",
    "Java",
    "Koa.js",
    "Laravel",
    "Meteor.js",
    "NestJS",
    "Node.js",
    "PHP",
    "Python",
    "Ruby",
    "Ruby on Rails",
    "Scala",
    "Shell scripting (Bash)",
    "Spring Boot",
    "Tcl",
    "WebSockets",
    "REST API",
  ],

  Mobile: [
    "Android Development",
    "AppGyver",
    "Appium",
    "Cordova",
    "Firebase SDK for Mobile",
    "Ionic",
    "Jetpack Compose",
    "Kotlin",
    "NativeScript",
    "Objective-C",
    "PhoneGap",
    "React Native",
    "Realm",
    "Swift",
    "SwiftUI",
    "Unity",
    "Wear OS",
    "Xamarin",
    "iOS Development",
    "React Native Navigation",
    "Flutter",
  ],

  Database: [
    "Amazon RDS",
    "Apache Kafka",
    "Cassandra",
    "CockroachDB",
    "Couchbase",
    "CouchDB",
    "Database Sharding",
    "DynamoDB",
    "Elasticsearch",
    "FaunaDB",
    "Firebase",
    "GraphQL with Database Integration",
    "IBM DB2",
    "InfluxDB",
    "MariaDB",
    "Microsoft SQL Server",
    "MongoDB",
    "MySQL",
    "Neo4j",
    "Oracle DB",
    "PostgresSQL",
    "Redis",
    "SQLite",
    "Supabase",
  ],

  "Cloud & DevOps": [
    "Alibaba Cloud",
    "AWS",
    "Google Cloud",
    "Ansible",
    "Apache",
    "Azure",
    "CI/CD",
    "CloudFormation",
    "Datadog",
    "DigitalOcean",
    "Docker",
    "Docker Swarm",
    "Grafana",
    "GitHub Actions",
    "GitLab CI",
    "Helm",
    "IBM Cloud",
    "Jenkins",
    "Kubernetes",
    "Linode",
    "New Relic",
    "Nginx",
    "Oracle Cloud",
    "Packer",
    "Prometheus",
    "Terraform",
    "Vault by HashiCorp",
    "Vercel",
    "Netlify",
    "CloudWatch",
    "S3",
    "Cloudflare",
    "EC2",
  ],

  "Tools & Others": [
    "AI/ML",
    "Airtable",
    "Adobe XD",
    "Asana",
    "Basecamp",
    "Bitbucket",
    "CircleCI",
    "ClickUp",
    "Docker Compose",
    "Figma",
    "Framer",
    "Git",
    "GitLab",
    "Jira",
    "Jest",
    "Linux",
    "LogRocket",
    "Monday.com",
    "Notion",
    "Photoshop",
    "Prettier",
    "Postman",
    "Sentry",
    "Slack",
    "Sketch",
    "SVN",
    "Trello",
    "VSCode",
    "Zsh",
    "Zeplin",
    "InVision",
    "Marvel App",
    "IntelliJ IDEA",
    "Unit Testing",
    "Integration Testing",
    "Software Documentation",
    "Data Structures",
    "Algorithms",
    "System Design",
    "Vite"
  ],

  "Soft Skills": [
    "Communication",
    "Leadership",
    "Teamwork",
    "Problem Solving",
    "Critical Thinking",
    "Time Management",
    "Project Management",
    "Analytical",
    "Creative",
    "Adaptable",
    "Detail-oriented",
    "Self-motivated",
    "Collaborative",
    "Mentoring",
    "Training",
    "Product Ownership",
    "Customer-centric Thinking",
  ],
};

// --------------- Aliases --------------

export const aliases: Record<string, string[]> = {
  // Frontend
  "alpine.js": ["alpine", "alpine.js"],
  angular: ["angular", "angularjs"],
  "backbone.js": ["backbone", "backbone.js"],
  bootstrap: ["bootstrap"],
  "css grid layout": ["css grid", "css grid layout"],
  "css modules": ["css modules"],
  "ember.js": ["ember", "ember.js"],
  eslint: ["eslint", "es lint"],
  gatsby: ["gatsby"],
  graphql: ["graphql", "gql"],
  "html/css": ["html/css", "html and css", "html css", "htmlcss"],
  javascript: ["js", "javascript", "vanilla js"],
  lit: ["lit"],
  litelement: ["litelement", "lit-element", "lit element"],
  "mithril.js": ["mithril", "mithril.js"],
  "next.js": ["next", "next.js", "nextjs"],
  "nuxt.js": ["nuxt", "nuxt.js", "nuxtjs"],
  postcss: ["postcss", "post css"],
  preact: ["preact"],
  react: ["react", "reactjs", "react.js"],
  redux: ["redux", "reduxjs"],
  "sass/scss": ["sass", "scss", "sass/scss"],
  "styled components": ["styled components", "styled-components"],
  "tailwind css": ["tailwind", "tailwindcss", "tailwind css"],
  typescript: ["ts", "typescript"],
  "vue.js": ["vue", "vuejs", "vue.js"],
  "web components": ["web components", "webcomponents"],
  webassembly: ["wasm", "webassembly", "web assembly"],
  webpack: ["webpack"],
  storybook: ["storybook"],
  "cross-browser compatibility": [
    "cross browser compatibility",
    "cross-browser",
  ],
  "responsive design": ["responsive design", "responsive"],
  "progressive enhancement": ["progressive enhancement"],
  "graceful degradation": ["graceful degradation"],
  "web accessibility": ["web accessibility", "a11y"],
  "website performance optimization": [
    "performance optimization",
    "website performance",
  ],

  // Backend
  "asp.net": ["asp.net", "asp net"],
  "c#": ["c#", "c sharp"],
  "c++": ["c++", "cpp"],
  django: ["django"],
  elixir: ["elixir"],
  "express.js": ["express", "express.js"],
  fastapi: ["fastapi"],
  flask: ["flask"],
  go: ["go", "golang"],
  "graphql api": ["graphql api", "graphql"],
  grpc: ["grpc", "gRPC"],
  java: ["java"],
  "koa.js": ["koa", "koa.js"],
  laravel: ["laravel"],
  "meteor.js": ["meteor", "meteor.js"],
  nestjs: ["nestjs"],
  "node.js": ["node", "nodejs", "node.js"],
  php: ["php"],
  python: ["python"],
  ruby: ["ruby"],
  "ruby on rails": ["rails", "ruby on rails", "ror"],
  scala: ["scala"],
  "shell scripting (bash)": ["bash", "shell scripting", "shell"],
  "spring boot": ["spring boot", "springboot"],
  tcl: ["tcl"],
  websockets: ["websockets", "web sockets"],
  "rest api": ["rest api", "restful api", "rest"],

  // Mobile
  "android development": ["android", "android development"],
  appgyver: ["appgyver"],
  appium: ["appium"],
  cordova: ["cordova"],
  "firebase sdk for mobile": [
    "firebase sdk",
    "firebase sdk for mobile",
    "firebase",
  ],
  ionic: ["ionic"],
  "jetpack compose": ["jetpack compose"],
  kotlin: ["kotlin"],
  nativescript: ["nativescript"],
  "objective-c": ["objective-c", "objc"],
  phonegap: ["phonegap"],
  "react native": ["react native", "reactnative"],
  realm: ["realm"],
  swift: ["swift"],
  swiftui: ["swiftui"],
  unity: ["unity"],
  "wear os": ["wear os", "wearos"],
  xamarin: ["xamarin"],
  "ios development": ["ios", "ios development", "iphone development"],
  "react native navigation": ["react native navigation"],
  flutter: ["flutter"],

  // Database
  "amazon rds": ["amazon rds", "rds"],
  "apache kafka": ["apache kafka", "kafka"],
  cassandra: ["cassandra"],
  cockroachdb: ["cockroachdb", "cockroach"],
  couchbase: ["couchbase"],
  couchdb: ["couchdb"],
  "database sharding": ["database sharding", "sharding"],
  dynamodb: ["dynamodb", "amazon dynamodb"],
  elasticsearch: ["elasticsearch", "elastic"],
  faunadb: ["faunadb"],
  firebase: ["firebase"],
  "graphql with database integration": [
    "graphql with database integration",
    "graphql database",
  ],
  "ibm db2": ["ibm db2", "db2"],
  influxdb: ["influxdb"],
  mariadb: ["mariadb"],
  "microsoft sql server": ["microsoft sql server", "sql server", "mssql"],
  mongodb: ["mongodb", "mongo"],
  mysql: ["mysql"],
  neo4j: ["neo4j"],
  "oracle db": ["oracle db", "oracle database"],
  postgresql: ["postgresql", "postgres", "pg"],
  redis: ["redis"],
  sqlite: ["sqlite"],
  supabase: ["supabase"],

  // Cloud & DevOps
  "alibaba cloud": ["alibaba cloud"],
  aws: ["amazon web services", "amazon aws", "aws"],
  "google cloud": ["gcp", "google cloud platform", "google cloud"],
  ansible: ["ansible"],
  apache: ["apache"],
  azure: ["azure", "microsoft azure"],
  "ci/cd": ["ci/cd", "cicd", "continuous integration", "continuous delivery"],
  cloudformation: ["cloudformation", "aws cloudformation"],
  datadog: ["datadog"],
  digitalocean: ["digitalocean", "digital ocean"],
  docker: ["docker"],
  "docker swarm": ["docker swarm"],
  grafana: ["grafana"],
  "github actions": ["github actions"],
  "gitlab ci": ["gitlab ci"],
  helm: ["helm"],
  "ibm cloud": ["ibm cloud"],
  jenkins: ["jenkins"],
  kubernetes: ["k8s", "kubernetes"],
  linode: ["linode"],
  "new relic": ["new relic"],
  nginx: ["nginx"],
  "oracle cloud": ["oracle cloud"],
  packer: ["packer"],
  prometheus: ["prometheus"],
  terraform: ["terraform"],
  "vault by hashicorp": ["vault", "vault by hashicorp"],
  vercel: ["vercel"],
  netlify: ["netlify"],
  cloudwatch: ["cloudwatch", "aws cloudwatch"],
  s3: ["s3", "amazon s3", "aws s3"],
  cloudflare: ["cloudflare"],
  ec2: ["ec2", "amazon ec2", "aws ec2"],

  // Tools & Others
  "ai/ml": ["artificial intelligence", "machine learning", "ml", "ai"],
  airtable: ["airtable"],
  "adobe xd": ["adobe xd"],
  asana: ["asana"],
  basecamp: ["basecamp"],
  bitbucket: ["bitbucket"],
  circleci: ["circleci"],
  clickup: ["clickup"],
  "docker compose": ["docker compose"],
  figma: ["figma"],
  framer: ["framer"],
  git: ["git", "github", "gitlab"],
  gitlab: ["gitlab"],
  jira: ["jira"],
  jest: ["jest"],
  linux: ["linux"],
  logrocket: ["logrocket"],
  "monday.com": ["monday.com"],
  notion: ["notion"],
  photoshop: ["photoshop"],
  prettier: ["prettier"],
  postman: ["postman"],
  sentry: ["sentry"],
  slack: ["slack"],
  sketch: ["sketch"],
  svn: ["svn", "subversion"],
  trello: ["trello"],
  vscode: ["vscode", "visual studio code"],
  zsh: ["zsh"],
  zeplin: ["zeplin"],
  invision: ["invision"],
  "marvel app": ["marvel app", "marvel"],
  "intellij idea": ["intellij", "intellij idea", "idea"],
  "unit testing": ["unit testing"],
  "integration testing": ["integration testing"],
  "software documentation": ["software documentation"],
  "data structures": ["data structures"],
  algorithms: ["algorithms"],

  // Soft Skills
  communication: ["communication", "communicating"],
  leadership: ["leadership"],
  teamwork: ["teamwork", "team work"],
  "problem solving": ["problem solving", "problem-solver"],
  "critical thinking": ["critical thinking"],
  "time management": ["time management"],
  "project management": ["project management"],
  analytical: ["analytical", "analytics"],
  creative: ["creative", "creativity"],
  adaptable: ["adaptable", "adaptability"],
  "detail-oriented": [
    "detail-oriented",
    "detail oriented",
    "attention to detail",
  ],
  "self-motivated": ["self-motivated", "self motivated", "self-driven"],
  collaborative: ["collaborative", "collaboration"],
  mentoring: ["mentoring", "mentor"],
  training: ["training"],
  "product ownership": ["product ownership"],
  "customer-centric thinking": [
    "customer-centric thinking",
    "customer focused",
    "customer centric",
  ],
};
